name: main
on: [push]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - run: ls -la
            - run: npm install
            - run: ls -la
